### ISSUE TITLE
`torch` is missing in `fateflow-ipcl` image

### ISSUE THREAD

**Issue by fangxiaoran** [FederatedAI/FATE-Builder#24]
It seems the below code would delete `torch` from `base-image`, `base-image-ipcl` and `fateflow-ipcl`, which leads some models (e.g. `hetero_sbt`) failed to import torch.
https://github.com/FederatedAI/FATE-Builder/blob/e5169a771e97b6f389a9c1f22cf44f889525cda9/docker-build/base/basic/Dockerfile#L38

Error messages:
> [ERROR] [2022-12-15 11:49:30,347] [Server] [16:139606326486784] - [base_worker.run] [line:113]: No module named 'torch'
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/worker/base_worker.py", line 111, in run
    result = self._run()
  File "/data/projects/fate/fateflow/python/fate_flow/worker/task_initializer.py", line 51, in _run
    parameters, user_specified_parameters = ProviderManager.get_component_parameters(dsl_parser=dsl_parser,
  File "/data/projects/fate/fateflow/python/fate_flow/manager/provider_manager.py", line 152, in get_component_parameters
    parameters = dsl_parser.parse_component_parameters(component_name,
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py", line 370, in parse_component_parameters
    parameters = self._init_component_setting(component_name,
  File "/data/projects/fate/fateflow/python/fate_flow/scheduler/dsl_parser.py", line 335, in _init_component_setting
    role_parameters = RuntimeConfParserUtil.get_component_parameters(provider,
  File "/data/projects/fate/fateflow/python/fate_flow/utils/runtime_conf_parse_util.py", line 102, in get_component_parameters
    conf["CodePath"] = provider.get(module, provider_components).get_run_obj_name(
  File "/data/projects/fate/fate/python/federatedml/components/components.py", line 133, in get_run_obj_name
    return self._get_runner(role).__name__
  File "/data/projects/fate/fate/python/federatedml/components/components.py", line 120, in _get_runner
    runner_class = self._role_to_runner_cls_getter[role]()
  File "/data/projects/fate/fate/python/federatedml/components/hetero_secure_boost.py", line 39, in hetero_secure_boost_host_runner
    from federatedml.ensemble import (HeteroSecureBoostingTreeHost)
  File "/data/projects/fate/fate/python/federatedml/ensemble/__init__.py", line 33, in <module>
    from federatedml.ensemble.basic_algorithms.decision_tree.homo.homo_decision_tree_aggregator import \
  File "/data/projects/fate/fate/python/federatedml/ensemble/basic_algorithms/decision_tree/homo/homo_decision_tree_aggregator.py", line 4, in <module>
    from federatedml.framework.homo.aggregator.secure_aggregator import SecureAggregatorClient, SecureAggregatorServer
  File "/data/projects/fate/fate/python/federatedml/framework/homo/aggregator/__init__.py", line 1, in <module>
    from federatedml.framework.homo.aggregator.secure_aggregator import SecureAggregatorClient, SecureAggregatorServer
  File "/data/projects/fate/fate/python/federatedml/framework/homo/aggregator/secure_aggregator.py", line 6, in <module>
    import torch as t
ModuleNotFoundError: No module named 'torch'

**Comment by owlet42** [comment]
https://github.com/FederatedAI/FATE-Builder/commit/1186e386963a92be15704d8e75d8c88ae0aafefd This commit fulfills this requirement
